language: objective-c
rvm: 1.9.3-p545 --create
branches:
  only:
  - "/release-/"
before_install:
- brew update
install:
- mkdir -p $(brew --repo)/Library/Taps
- brew tap $TRAVIS_REPO_SLUG
- cd $(brew --repo)/Library/Taps/$(echo $TRAVIS_REPO_SLUG | tr '[:upper:]' '[:lower:]')
- git checkout -b gnuchains-tools origin/gnuchains-tools
- brew tap --repair
env:
  matrix:
  - PACKAGE=pf-gnuchains4x-arm-eabi-tools
  - PACKAGE=pf-gnuchains4x-arm-elf-tools
  - PACKAGE=pf-gnuchains4x-avr-elf-tools
  - PACKAGE=pf-gnuchains4x-bfin-elf-tools
#  - PACKAGE=pf-gnuchains4x-cr16-elf-tools
  - PACKAGE=pf-gnuchains4x-fr30-elf-tools
  - PACKAGE=pf-gnuchains4x-h8300-elf-tools
  - PACKAGE=pf-gnuchains4x-i386-elf-tools
  - PACKAGE=pf-gnuchains4x-lm32-elf-tools
  - PACKAGE=pf-gnuchains4x-m32c-elf-tools
  - PACKAGE=pf-gnuchains4x-m32r-elf-tools
  - PACKAGE=pf-gnuchains4x-m68k-elf-tools
  - PACKAGE=pf-gnuchains4x-microblaze-elf-tools
  - PACKAGE=pf-gnuchains4x-mips-elf-tools
  - PACKAGE=pf-gnuchains4x-mips64-elf-tools
  - PACKAGE=pf-gnuchains4x-mips64-toppershrp-tools
  - PACKAGE=pf-gnuchains4x-nios2-elf-tools
  - PACKAGE=pf-gnuchains4x-powerpc-elf-tools
  - PACKAGE=pf-gnuchains4x-rx-elf-tools
  - PACKAGE=pf-gnuchains4x-sh-elf-tools
  - PACKAGE=pf-gnuchains4x-v850-elf-tools
  - PACKAGE=pf-gnuchains4x-xstormy16-elf-tools
  - PACKAGE=pf-gnuchains4x-xtensa-elf-tools
  global:
    secure: ChhAvkF13Jp9wNDCMx64eYC2MXQqM+SpO76FJXPGntoyHSlV8B9qu1KEcXU+d6LJVSWVki4d1N0B3cmfXn1vg2N8EY5hyohDt/IBYYHz/u+bbAMcrieKA1UATzP3/TVt0y0jGwmsti2iSECLgGRqqw1n/1jP1Udgfha/AaU7Z/A=
script:
- brew audit $PACKAGE
- brew install --build-bottle -v $PACKAGE
- brew test $PACKAGE
- bottled_file=$(brew bottle --rb $PACKAGE | head -1 | awk '{ gsub(/...$/, "", $3); print $3}')
deploy:
  edge: true
  provider: releases
  api-key:
  - secure: PwKJFynBZ8tK6ScOM5NCEv39JDVGupIrChiR6gyPlzwE2Q64OivmrM/N5IXIZYJyIh7ZHZ7eVOxTbVCmJZxLj1kMD4W+jj94y3HCaRog+eJRG2vapd+EtatCZFdrF2ccnWzO31hu3vLtZCIs3nD/vb0NyYexswJ3zzEcuqAp4iU=
  file: "$bottled_file"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_deploy:
- bottle_rb=$(pwd)/*.bottle.rb
- perl -pi -e 's|bottle do$|bottle do\n    root_url "https://github.com/PizzaFactory/homebrew-commandline/releases/download/'$(git tag --points-at HEAD)'"|' $bottle_rb
- echo $bottle_rb
- cat $bottle_rb
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
- openssl aes-256-cbc -k "$SERVER_KEY" -in .travis/deploy_key.enc -d -a -out deploy.key
- cp deploy.key ~/.ssh/
- chmod 600 ~/.ssh/deploy.key
- cd $(brew --prefix)/Library/Taps/pizzafactory/homebrew-commandline/
- git remote add github-push git@github.com:PizzaFactory/homebrew-commandline.git
- git pull
- brew bottle --merge --write $bottle_rb
- git pull
- git push github-push --all
- git pull
- git push github-push --all
- git pull
- git push github-push --all
