language: objective-c
rvm: 1.9.3-p545 --create
branches:
  only:
  - /release-/
  - develop
before_install:
- brew update
install:
- brew tap $TRAVIS_REPO_SLUG
env:
  matrix:
  - PACKAGE=bfin-gdbproxy
  - PACKAGE=kz_h8write
  - PACKAGE=pf-gnuchains4x-arm-eabi
  - PACKAGE=pf-gnuchains4x-arm-elf
  - PACKAGE=pf-gnuchains4x-avr-elf
  - PACKAGE=pf-gnuchains4x-bfin-elf
#  - PACKAGE=pf-gnuchains4x-cr16-elf
  - PACKAGE=pf-gnuchains4x-fr30-elf
  - PACKAGE=pf-gnuchains4x-h8300-elf
  - PACKAGE=pf-gnuchains4x-i386-elf
  - PACKAGE=pf-gnuchains4x-lm32-elf
  - PACKAGE=pf-gnuchains4x-m32c-elf
  - PACKAGE=pf-gnuchains4x-m32r-elf
  - PACKAGE=pf-gnuchains4x-m68k-elf
  - PACKAGE=pf-gnuchains4x-microblaze-elf
  - PACKAGE=pf-gnuchains4x-mips-elf
  - PACKAGE=pf-gnuchains4x-mips64-elf
  - PACKAGE=pf-gnuchains4x-mips64-toppershrp
  - PACKAGE=pf-gnuchains4x-nios2-elf
  - PACKAGE=pf-gnuchains4x-powerpc-elf
  - PACKAGE=pf-gnuchains4x-rx-elf
  - PACKAGE=pf-gnuchains4x-sh-elf
  - PACKAGE=pf-gnuchains4x-v850-elf
  - PACKAGE=pf-gnuchains4x-xstormy16-elf
  - PACKAGE=pf-gnuchains4x-xtensa-elf
  - PACKAGE=stlink
  - PACKAGE=urjtag
  global:
    secure: W45EELxImy/4VWYGIAMYRp23onrw6Bu/ALMA45MneHigTLdsiKMb2DgzJ1NVCGRnk3Yvl0LlBmWDJyz6FVerDm6fBplyN82BF3Q1gV2FrDcnkAvbz1nKshTbuQNLXYQ108qhCHJV/WTsycglKfYeLzmMrViE3vq69eozp8Qu2G8=
script:
- brew audit $PACKAGE.rb
- travis_wait 50 brew install --build-bottle $PACKAGE.rb
- brew test $PACKAGE.rb
- bottled_file=$(brew bottle --rb $PACKAGE.rb | head -1 | awk '{ gsub(/...$/, "", $3);
  print $3}')
deploy:
  edge: true
  provider: releases
  api-key:
  - secure: MSmHrVWM6aAOfohOZc7fsfUKISYkjmZMlfv5uqcuUS1/c6E2ExYFyC9A/CSrc8VwjdlDf+nMtl/CZwNLLsf70eNajAhQFxFgDqFr/ScZXR8CaALceeTsLlm8nQpaMSDzDBNzbQV3BU+RiVMT1Zi5MtEexOYQabeoEa3/gmXxwzA=
  file: $bottled_file
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_deploy:
# Add root_url
- "bottle_rb=$(pwd)/*.bottle.rb"
- echo $bottle_rb
- cat $bottle_rb
# decrypt a key
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
- openssl aes-256-cbc -k "$SERVER_KEY" -in .travis/deploy_key.enc -d -a -out deploy.key
- cp deploy.key ~/.ssh/
- chmod 600 ~/.ssh/deploy.key
# Update the formula
- tag=$(git tag --points-at HEAD)
- cd $(brew --prefix)/Library/Taps/pizzafactory/homebrew-commandline/
- echo 's|bottle do$|bottle do\n    root_url "https://github.com/PizzaFactory/homebrew-commandline/releases/download/'$tag'"|' > perl_script
- git remote add github-push git@github.com:PizzaFactory/homebrew-commandline.git
- git pull --rebase
- brew bottle --merge --write $bottle_rb
# Hack start>>>>
- perl -pi perl_script $PACKAGE.rb
- git add $PACKAGE.rb
- git commit --amend -C HEAD
# <<<<Hack end
- git pull --rebase
- git push github-push --all
# to make sure...
- git pull --rebase
- git push github-push --all
- git pull --rebase
- git push github-push --all
