language: objective-c
rvm: 1.9.3-p545 --create
branches:
  only:
  - /release-/
before_install:
- brew update
install:
- mkdir -p $(brew --repo)/Library/Taps
- brew tap $TRAVIS_REPO_SLUG
- cd $(brew --repo)/Library/Taps/$(echo $TRAVIS_REPO_SLUG | tr '[:upper:]' '[:lower:]')
- git checkout -b gnuchains-tools origin/gnuchains-tools
- brew tap --repair
- cd -
env:
  matrix:
  - PACKAGE=pf-gnuchains4x-arm-eabi-lib
  - PACKAGE=pf-gnuchains4x-arm-elf-lib
  - PACKAGE=pf-gnuchains4x-avr-elf-lib
  - PACKAGE=pf-gnuchains4x-bfin-elf-lib
#  - PACKAGE=pf-gnuchains4x-cr16-elf-lib
  - PACKAGE=pf-gnuchains4x-fr30-elf-lib
  - PACKAGE=pf-gnuchains4x-h8300-elf-lib
  - PACKAGE=pf-gnuchains4x-i386-elf-lib
  - PACKAGE=pf-gnuchains4x-lm32-elf-lib
  - PACKAGE=pf-gnuchains4x-m32c-elf-lib
  - PACKAGE=pf-gnuchains4x-m32r-elf-lib
  - PACKAGE=pf-gnuchains4x-m68k-elf-lib
  - PACKAGE=pf-gnuchains4x-microblaze-elf-lib
  - PACKAGE=pf-gnuchains4x-mips-elf-lib
  - PACKAGE=pf-gnuchains4x-mips64-elf-lib
  - PACKAGE=pf-gnuchains4x-mips64-toppershrp-lib
  - PACKAGE=pf-gnuchains4x-nios2-elf-lib
  - PACKAGE=pf-gnuchains4x-powerpc-elf-lib
  - PACKAGE=pf-gnuchains4x-rx-elf-lib
  - PACKAGE=pf-gnuchains4x-sh-elf-lib
  - PACKAGE=pf-gnuchains4x-v850-elf-lib
  - PACKAGE=pf-gnuchains4x-xstormy16-elf-lib
  - PACKAGE=pf-gnuchains4x-xtensa-elf-lib
  global:
    secure: eyjnztPwfyykADsbJu5Wv+KLTOhyC2rhj/VSW5iIiyc5Wqe+D7EdgjD8esXm5oJBnXEdgoxydLKY2keBNjUX+VRJWF66Qs4T9X+vmEiX+ONaziZIiARN0jRyIR7dcGNjEdUE7U7Z7CNH4G8raFeibo9wg5N2XnuM3XhDXINjavo=
script:
- brew audit $PACKAGE.rb
- travis_wait 50 brew install --build-bottle $PACKAGE.rb
#- brew test $PACKAGE.rb
- bottled_file=$(brew bottle --rb $PACKAGE.rb | head -1 | awk '{ gsub(/...$/, "", $3);
  print $3}')
deploy:
  edge: true
  provider: releases
  api-key:
  - secure: McgbuPp1Wva9i0tch4gqxRfNjg9Wbclu1feJ1f0AxWaVbX1tJuQVhq4NLQX12mfvTRqZGrZaxVpmUpEFrbOah9x/dvl4V4LxwAMO9xvMCoX0GVdHEIeHK7gWWexSQQJKTvfX+k1Jl8jnn925k6f4VBd0fPWMyu3ClRe9iAs8+yw=
  file: "$bottled_file"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_deploy:
# Add root_url
- "bottle_rb=$(pwd)/*.bottle.rb"
- echo $bottle_rb
- cat $bottle_rb
# decrypt a key
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
- openssl aes-256-cbc -k "$SERVER_KEY" -in .travis/deploy_key.enc -d -a -out deploy.key
- cp deploy.key ~/.ssh/
- chmod 600 ~/.ssh/deploy.key
# Update the formula
- tag=$(git tag --points-at HEAD)
- cd $(brew --prefix)/Library/Taps/pizzafactory/homebrew-commandline/
- git checkout -b gnuchains-libs origin/gnuchains-libs
- brew tap --repair
- echo 's|bottle do$|bottle do\n    root_url "https://github.com/PizzaFactory/homebrew-commandline/releases/download/'$tag'"|' > perl_script
- git remote add github-push git@github.com:PizzaFactory/homebrew-commandline.git
- git pull
- brew bottle --merge --write $bottle_rb
# Hack start>>>>
- perl -pi perl_script $PACKAGE.rb
- git add $PACKAGE.rb
- git commit --amend -C HEAD
# <<<<Hack end
- git pull --rebase
- git push github-push --all
# to make sure...
- git pull --rebase
- git push github-push --all
- git pull --rebase
- git push github-push --all
