language: objective-c
rvm: 1.9.3-p545 do rvm gemset create
before_install:
- brew update
install:
- mkdir -p $(brew --repo)/Library/Taps
- ln -s $PWD $(brew --repo)/Library/Taps/travis-testtap
- brew tap $TRAVIS_REPO_SLUG
env:
  matrix:
  - PACKAGE=urjtag
  - PACKAGE=pf-gnuchains4x-arm-eabi
  - PACKAGE=pf-gnuchains4x-arm-elf
  - PACKAGE=pf-gnuchains4x-avr-elf
  - PACKAGE=pf-gnuchains4x-bfin-elf
  - PACKAGE=pf-gnuchains4x-cr16-elf
  - PACKAGE=pf-gnuchains4x-fr30-elf
  - PACKAGE=pf-gnuchains4x-h8300-elf
  - PACKAGE=pf-gnuchains4x-i386-elf
  - PACKAGE=pf-gnuchains4x-lm32-elf
  - PACKAGE=pf-gnuchains4x-m32c-elf
  - PACKAGE=pf-gnuchains4x-m32r-elf
  - PACKAGE=pf-gnuchains4x-m68k-elf
  - PACKAGE=pf-gnuchains4x-microblaze-elf
  - PACKAGE=pf-gnuchains4x-mips-elf
  - PACKAGE=pf-gnuchains4x-mips64
  - PACKAGE=pf-gnuchains4x-nios2-elf
  - PACKAGE=pf-gnuchains4x-powerpc-elf
  - PACKAGE=pf-gnuchains4x-rx-elf
  - PACKAGE=pf-gnuchains4x-sh-elf
  - PACKAGE=pf-gnuchains4x-topperhrp
  - PACKAGE=pf-gnuchains4x-v850-elf
  - PACKAGE=pf-gnuchains4x-xstormy16-elf
  - PACKAGE=pf-gnuchains4x-xtensa-elf
  global:
script:
- brew audit $PACKAGE
- brew install --build-bottle -v $PACKAGE
- brew test $PACKAGE
- brew bottle $PACKAGE
deploy:
  edge: true
  provider: releases
  api-key:
    - secure:KSxUOxDlEBc4SzlSpI3Y4zkss5iX0bYlmaqJCQyUE6lwDcZM1skdTc5JMSCA8iPxzTGnJ7KbYUxpigwpE0r3JyYiXZOJQyXIg/gZ1XEDrXBif3vda8l1sOxYaoajh300arcV+RtKj4F8VmmdM1jjywYRazWpVpWmewtG0u/b+pM=
  file: '*.tar.gz'
  on:
    tags: true
    all_branches: true
