language: objective-c
rvm: 1.9.3-p545 --create
branches:
  only:
  - "/release-/"
before_install:
- brew update
install:
- mkdir -p $(brew --repo)/Library/Taps
- ln -s $PWD $(brew --repo)/Library/Taps/travis-testtap
- brew tap $TRAVIS_REPO_SLUG
env:
  matrix:
  - PACKAGE=pf-gnuchains4x-arm-eabi-lib
  - PACKAGE=pf-gnuchains4x-arm-elf-lib
  - PACKAGE=pf-gnuchains4x-avr-elf-lib
  - PACKAGE=pf-gnuchains4x-bfin-elf-lib
#  - PACKAGE=pf-gnuchains4x-cr16-elf-lib
  - PACKAGE=pf-gnuchains4x-fr30-elf-lib
  - PACKAGE=pf-gnuchains4x-h8300-elf-lib
  - PACKAGE=pf-gnuchains4x-i386-elf-lib
  - PACKAGE=pf-gnuchains4x-lm32-elf-lib
  - PACKAGE=pf-gnuchains4x-m32c-elf-lib
  - PACKAGE=pf-gnuchains4x-m32r-elf-lib
  - PACKAGE=pf-gnuchains4x-m68k-elf-lib
  - PACKAGE=pf-gnuchains4x-microblaze-elf-lib
  - PACKAGE=pf-gnuchains4x-mips-elf-lib
  - PACKAGE=pf-gnuchains4x-mips64-elf-lib
  - PACKAGE=pf-gnuchains4x-mips64-toppershrp-lib
  - PACKAGE=pf-gnuchains4x-nios2-elf-lib
  - PACKAGE=pf-gnuchains4x-powerpc-elf-lib
  - PACKAGE=pf-gnuchains4x-rx-elf-lib
  - PACKAGE=pf-gnuchains4x-sh-elf-lib
  - PACKAGE=pf-gnuchains4x-v850-elf-lib
  - PACKAGE=pf-gnuchains4x-xstormy16-elf-lib
  - PACKAGE=pf-gnuchains4x-xtensa-elf-lib
  global:
    secure: ChhAvkF13Jp9wNDCMx64eYC2MXQqM+SpO76FJXPGntoyHSlV8B9qu1KEcXU+d6LJVSWVki4d1N0B3cmfXn1vg2N8EY5hyohDt/IBYYHz/u+bbAMcrieKA1UATzP3/TVt0y0jGwmsti2iSECLgGRqqw1n/1jP1Udgfha/AaU7Z/A=
script:
- brew audit $PACKAGE
- brew install --build-bottle -v $PACKAGE
#- brew test $PACKAGE
- bottled_file=$(brew bottle $PACKAGE | head -1 | awk '{ gsub(/...$/, "", $3); print $3}')
deploy:
  edge: true
  provider: releases
  api-key:
  - secure: McgbuPp1Wva9i0tch4gqxRfNjg9Wbclu1feJ1f0AxWaVbX1tJuQVhq4NLQX12mfvTRqZGrZaxVpmUpEFrbOah9x/dvl4V4LxwAMO9xvMCoX0GVdHEIeHK7gWWexSQQJKTvfX+k1Jl8jnn925k6f4VBd0fPWMyu3ClRe9iAs8+yw=
  file: "$bottled_file"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_deploy:
- bottle_rb=$(pwd)/*.bottle.rb
- perl -pi -e 's|bottle do$|bottle do\n    root_url "https://github.com/PizzaFactory/homebrew-commandline/releases/download/'$(git tag --points-at HEAD)'"|' $bottle_rb
- echo $bottle_rb
- cat $bottle_rb
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
- openssl aes-256-cbc -k "$SERVER_KEY" -in .travis/deploy_key.enc -d -a -out deploy.key
- cp deploy.key ~/.ssh/
- chmod 600 ~/.ssh/deploy.key
- cd $(brew --prefix)/Library/Taps/pizzafactory/homebrew-commandline/
- git remote add github-push git@github.com:PizzaFactory/homebrew-commandline.git
- git pull
- brew bottle --merge --write $bottle_rb
- git pull
- git push github-push --all
- git pull
- git push github-push --all
- git pull
- git push github-push --all
